# Generated by Django 4.1.4 on 2023-02-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usermodel_is_active_alter_usermodel_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='uid',
            field=models.CharField(max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='uname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='upass',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
